# Generated by Django 5.2 on 2025-10-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
    ]
