# Generated by Django 5.2 on 2025-10-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_alter_category_options_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Скидка"
            ),
        ),
    ]
