# Generated by Django 5.2 on 2025-10-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_alter_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=4, verbose_name="Скидка"
            ),
        ),
    ]
