# Generated by Django 5.2 on 2025-10-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_alter_product_discount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("id",),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
